server.port= 8082
# MySQL ??
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

########### DB?? ??? ??? spring?? ?????? ??? ?? ? ?????##################
# DB Source URL
spring.datasource.url=jdbc:mysql://jobfair.czl6tjaswlln.ap-northeast-2.rds.amazonaws.com:3306/fairdb?useSSL=false&useUnicode=true&&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
# DB username
spring.datasource.username=admin
# DB password
spring.datasource.password=admin123

############ DB?? ??? ??? spring?? ?????? ??? ?? ? ?????##################
## DB Source URL
#spring.datasource.url=jdbc:mysql://localhost:3306/EC2????useSSL=false&useUnicode=true&&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
## DB username
#spring.datasource.username=spring
## DB password
#spring.datasource.password=spring

##??xml? ?? - classpath:/??? ??? ??? ???
mybatis.mapper-locations=classpath:/mapper/**/*.xml

##????? ??? ???? ????
mybatis.type-aliases-package=com.sungjin.jobfair.command


######## ????? ?? ########
# 1. ????? ?? ?? ?? true : ??, false : ??
spring.servlet.multipart.enabled=true
# 2. ?? ??? ?? ??
spring.servlet.multipart.max-file-size=50MB
# 3. ??? ??? ?? ??
spring.servlet.multipart.max-request-size=50MB
# 4. ???? ??? ??? ??????
project.uploadpath=C:/bootupload

######## AWS S3 Setting #########
cloud.aws.credentials.access-key=AKIAUE3PMIBE6BGBY6NS
cloud.aws.credentials.secret-key=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
cloud.aws.s3.bucket=mj-final-bucket
cloud.aws.region.static=ap-northeast-2
cloud.aws.stack.auto=false
